.functor timestampSeconds(t:symbol):number
.functor toLower(t:symbol):symbol

.decl time(timestamp: symbol)
.decl seconds(secs: number)
.decl string(s: symbol)
.decl lower(s: symbol)


time("2021-01-05 03:22:51").
seconds(@timestampSeconds(t)) :- time(t).

string("Mixed case").
string("UPPER!").

lower(@toLower(s)) :- string(s).

.output seconds(IO=stdout)
.output lower(IO=stdout)
.output lower(IO=sqlite, filename="time.db")
